<?xml version="1.0" encoding="utf-8"?><Database Name="validations" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=validations;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="validationsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exercise" Member="Exercises">
    <Type Name="Exercise">
      <Column Name="exerciseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="moduleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exerciseName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="exerciseDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="exerciseCategory" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="exerciseStatus" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="exercisePosition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exercise_Task" Member="Tasks" ThisKey="exerciseId" OtherKey="exerciseId" Type="Task" />
      <Association Name="Module_Exercise" Member="Module" ThisKey="moduleId" OtherKey="moduleId" Type="Module" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module">
      <Column Name="moduleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="moduleName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="moduleDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="moduleStatus" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="modulePosition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Module_Exercise" Member="Exercises" ThisKey="moduleId" OtherKey="moduleId" Type="Exercise" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="taskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="exerciseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="taskName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="taskDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taskStatus" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="taskPosition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exercise_Task" Member="Exercise" ThisKey="exerciseId" OtherKey="exerciseId" Type="Exercise" IsForeignKey="true" />
    </Type>
  </Table>
</Database>